---
# Molecule converge playbook for default scenario
# This is the main playbook that gets tested

- name: Converge - Test sample_playbook.yml
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    # Test with custom message to verify variable handling
    sample_message: "Hello from Molecule test"
    # Use fixed temp directory for idempotent testing
    temp_dir_path: "/tmp/molecule_test_sandbox"

  tasks:
    - name: Include the sample playbook tasks
      ansible.builtin.include_role:
        name: ans_dev_sandbox_role

    - name: Verify role execution
      ansible.builtin.debug:
        msg: "Role ans_dev_sandbox_role executed successfully"

